/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.kuleuven.rodinia.dsl.services.LuaGrammarAccess;

public class LuaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LuaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.kuleuven.rodinia.dsl.parser.antlr.internal.InternalLuaParser createParser(XtextTokenStream stream) {
		return new be.kuleuven.rodinia.dsl.parser.antlr.internal.InternalLuaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Chunk";
	}
	
	public LuaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LuaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
