/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuaUiModule extends be.kuleuven.rodinia.dsl.ui.AbstractLuaUiModule {
	public LuaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
