/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RfsmRuntimeModule extends be.kuleuven.rodinia.dsl.AbstractRfsmRuntimeModule {

}
