/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RfsmGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class HyperGraphElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HyperGraph");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGraphKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHyperVerticesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHyperVerticesStateParserRuleCall_3_0 = (RuleCall)cHyperVerticesAssignment_3.eContents().get(0);
		private final Assignment cHyperEdgesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHyperEdgesTransitionParserRuleCall_4_0 = (RuleCall)cHyperEdgesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////this grammar is only for testing purposes!!
		////todo: 
		////define graph setup
		////create initial connector transition
		////remove connectors, but do create junctions
		//HyperGraph:
		//	"Graph" name=ID "{" hyperVertices+= //can have only one root state
		//	State //(hyperEdges += Connector)*
		//	hyperEdges+=Transition* "}";
		public ParserRule getRule() { return rule; }

		//"Graph" name=ID "{" hyperVertices+= //can have only one root state
		//State //(hyperEdges += Connector)*
		//hyperEdges+=Transition* "}"
		public Group getGroup() { return cGroup; }

		//"Graph"
		public Keyword getGraphKeyword_0() { return cGraphKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//hyperVertices+= //can have only one root state
		//State
		public Assignment getHyperVerticesAssignment_3() { return cHyperVerticesAssignment_3; }

		////can have only one root state
		//State
		public RuleCall getHyperVerticesStateParserRuleCall_3_0() { return cHyperVerticesStateParserRuleCall_3_0; }

		//hyperEdges+=Transition*
		public Assignment getHyperEdgesAssignment_4() { return cHyperEdgesAssignment_4; }

		//Transition
		public RuleCall getHyperEdgesTransitionParserRuleCall_4_0() { return cHyperEdgesTransitionParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSubHyperVerticesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSubHyperVerticesStateParserRuleCall_3_0 = (RuleCall)cSubHyperVerticesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEntryKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEntryAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEntryFunctionParserRuleCall_4_1_0 = (RuleCall)cEntryAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDooKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDooAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDooFunctionParserRuleCall_5_1_0 = (RuleCall)cDooAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExitKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExitAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cExitFunctionParserRuleCall_6_1_0 = (RuleCall)cExitAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//State:
		//	"state" name=ID "{" subHyperVertices+=State* ("entry:" entry=Function)? ("doo:" doo=Function)? ("exit:"
		//	exit=Function)? "}";
		public ParserRule getRule() { return rule; }

		//"state" name=ID "{" subHyperVertices+=State* ("entry:" entry=Function)? ("doo:" doo=Function)? ("exit:" exit=Function)?
		//"}"
		public Group getGroup() { return cGroup; }

		//"state"
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//subHyperVertices+=State*
		public Assignment getSubHyperVerticesAssignment_3() { return cSubHyperVerticesAssignment_3; }

		//State
		public RuleCall getSubHyperVerticesStateParserRuleCall_3_0() { return cSubHyperVerticesStateParserRuleCall_3_0; }

		//("entry:" entry=Function)?
		public Group getGroup_4() { return cGroup_4; }

		//"entry:"
		public Keyword getEntryKeyword_4_0() { return cEntryKeyword_4_0; }

		//entry=Function
		public Assignment getEntryAssignment_4_1() { return cEntryAssignment_4_1; }

		//Function
		public RuleCall getEntryFunctionParserRuleCall_4_1_0() { return cEntryFunctionParserRuleCall_4_1_0; }

		//("doo:" doo=Function)?
		public Group getGroup_5() { return cGroup_5; }

		//"doo:"
		public Keyword getDooKeyword_5_0() { return cDooKeyword_5_0; }

		//doo=Function
		public Assignment getDooAssignment_5_1() { return cDooAssignment_5_1; }

		//Function
		public RuleCall getDooFunctionParserRuleCall_5_1_0() { return cDooFunctionParserRuleCall_5_1_0; }

		//("exit:" exit=Function)?
		public Group getGroup_6() { return cGroup_6; }

		//"exit:"
		public Keyword getExitKeyword_6_0() { return cExitKeyword_6_0; }

		//exit=Function
		public Assignment getExitAssignment_6_1() { return cExitAssignment_6_1; }

		//Function
		public RuleCall getExitFunctionParserRuleCall_6_1_0() { return cExitFunctionParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Connector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Connector:
		//	"connector" name=ID "{" "}";
		public ParserRule getRule() { return rule; }

		//"connector" name=ID "{" "}"
		public Group getGroup() { return cGroup; }

		//"connector"
		public Keyword getConnectorKeyword_0() { return cConnectorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSourceStateCrossReference_2_0 = (CrossReference)cSourceAssignment_2.eContents().get(0);
		private final RuleCall cSourceStateQualifiedNameParserRuleCall_2_0_1 = (RuleCall)cSourceStateCrossReference_2_0.eContents().get(1);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTargetStateCrossReference_4_0 = (CrossReference)cTargetAssignment_4.eContents().get(0);
		private final RuleCall cTargetStateQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cTargetStateCrossReference_4_0.eContents().get(1);
		private final Assignment cEventsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cEventsEventParserRuleCall_5_0 = (RuleCall)cEventsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cGuardKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cGuardAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cGuardFunctionParserRuleCall_6_1_0 = (RuleCall)cGuardAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cEffectKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cEffectAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cEffectFunctionParserRuleCall_7_1_0 = (RuleCall)cEffectAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPriorityKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPriority_numberAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPriority_numberINTTerminalRuleCall_8_1_0 = (RuleCall)cPriority_numberAssignment_8_1.eContents().get(0);
		
		//Transition:
		//	"transition" "from" source+=[State|QualifiedName] "to" target+=[State|QualifiedName] events+=Event* ("guard:"
		//	guard=Function)? ("effect:" effect=Function)? ("priority" priority_number=INT)?;
		public ParserRule getRule() { return rule; }

		//"transition" "from" source+=[State|QualifiedName] "to" target+=[State|QualifiedName] events+=Event* ("guard:"
		//guard=Function)? ("effect:" effect=Function)? ("priority" priority_number=INT)?
		public Group getGroup() { return cGroup; }

		//"transition"
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }

		//"from"
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }

		//source+=[State|QualifiedName]
		public Assignment getSourceAssignment_2() { return cSourceAssignment_2; }

		//[State|QualifiedName]
		public CrossReference getSourceStateCrossReference_2_0() { return cSourceStateCrossReference_2_0; }

		//QualifiedName
		public RuleCall getSourceStateQualifiedNameParserRuleCall_2_0_1() { return cSourceStateQualifiedNameParserRuleCall_2_0_1; }

		//"to"
		public Keyword getToKeyword_3() { return cToKeyword_3; }

		//target+=[State|QualifiedName]
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }

		//[State|QualifiedName]
		public CrossReference getTargetStateCrossReference_4_0() { return cTargetStateCrossReference_4_0; }

		//QualifiedName
		public RuleCall getTargetStateQualifiedNameParserRuleCall_4_0_1() { return cTargetStateQualifiedNameParserRuleCall_4_0_1; }

		//events+=Event*
		public Assignment getEventsAssignment_5() { return cEventsAssignment_5; }

		//Event
		public RuleCall getEventsEventParserRuleCall_5_0() { return cEventsEventParserRuleCall_5_0; }

		//("guard:" guard=Function)?
		public Group getGroup_6() { return cGroup_6; }

		//"guard:"
		public Keyword getGuardKeyword_6_0() { return cGuardKeyword_6_0; }

		//guard=Function
		public Assignment getGuardAssignment_6_1() { return cGuardAssignment_6_1; }

		//Function
		public RuleCall getGuardFunctionParserRuleCall_6_1_0() { return cGuardFunctionParserRuleCall_6_1_0; }

		//("effect:" effect=Function)?
		public Group getGroup_7() { return cGroup_7; }

		//"effect:"
		public Keyword getEffectKeyword_7_0() { return cEffectKeyword_7_0; }

		//effect=Function
		public Assignment getEffectAssignment_7_1() { return cEffectAssignment_7_1; }

		//Function
		public RuleCall getEffectFunctionParserRuleCall_7_1_0() { return cEffectFunctionParserRuleCall_7_1_0; }

		//("priority" priority_number=INT)?
		public Group getGroup_8() { return cGroup_8; }

		//"priority"
		public Keyword getPriorityKeyword_8_0() { return cPriorityKeyword_8_0; }

		//priority_number=INT
		public Assignment getPriority_numberAssignment_8_1() { return cPriority_numberAssignment_8_1; }

		//INT
		public RuleCall getPriority_numberINTTerminalRuleCall_8_1_0() { return cPriority_numberINTTerminalRuleCall_8_1_0; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOneventKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEventliteralAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEventliteralSTRINGTerminalRuleCall_1_0 = (RuleCall)cEventliteralAssignment_1.eContents().get(0);
		
		//Event:
		//	"onevent" eventliteral=STRING;
		public ParserRule getRule() { return rule; }

		//"onevent" eventliteral=STRING
		public Group getGroup() { return cGroup; }

		//"onevent"
		public Keyword getOneventKeyword_0() { return cOneventKeyword_0; }

		//eventliteral=STRING
		public Assignment getEventliteralAssignment_1() { return cEventliteralAssignment_1; }

		//STRING
		public RuleCall getEventliteralSTRINGTerminalRuleCall_1_0() { return cEventliteralSTRINGTerminalRuleCall_1_0; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Function");
		private final Assignment cSourcecodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSourcecodeSTRINGTerminalRuleCall_0 = (RuleCall)cSourcecodeAssignment.eContents().get(0);
		
		//Function:
		//	sourcecode=STRING;
		public ParserRule getRule() { return rule; }

		//sourcecode=STRING
		public Assignment getSourcecodeAssignment() { return cSourcecodeAssignment; }

		//STRING
		public RuleCall getSourcecodeSTRINGTerminalRuleCall_0() { return cSourcecodeSTRINGTerminalRuleCall_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private HyperGraphElements pHyperGraph;
	private StateElements pState;
	private ConnectorElements pConnector;
	private TransitionElements pTransition;
	private EventElements pEvent;
	private FunctionElements pFunction;
	private QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public RfsmGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("be.kuleuven.rodinia.dsl.Rfsm".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////this grammar is only for testing purposes!!
	////todo: 
	////define graph setup
	////create initial connector transition
	////remove connectors, but do create junctions
	//HyperGraph:
	//	"Graph" name=ID "{" hyperVertices+= //can have only one root state
	//	State //(hyperEdges += Connector)*
	//	hyperEdges+=Transition* "}";
	public HyperGraphElements getHyperGraphAccess() {
		return (pHyperGraph != null) ? pHyperGraph : (pHyperGraph = new HyperGraphElements());
	}
	
	public ParserRule getHyperGraphRule() {
		return getHyperGraphAccess().getRule();
	}

	//State:
	//	"state" name=ID "{" subHyperVertices+=State* ("entry:" entry=Function)? ("doo:" doo=Function)? ("exit:"
	//	exit=Function)? "}";
	public StateElements getStateAccess() {
		return (pState != null) ? pState : (pState = new StateElements());
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//Connector:
	//	"connector" name=ID "{" "}";
	public ConnectorElements getConnectorAccess() {
		return (pConnector != null) ? pConnector : (pConnector = new ConnectorElements());
	}
	
	public ParserRule getConnectorRule() {
		return getConnectorAccess().getRule();
	}

	//Transition:
	//	"transition" "from" source+=[State|QualifiedName] "to" target+=[State|QualifiedName] events+=Event* ("guard:"
	//	guard=Function)? ("effect:" effect=Function)? ("priority" priority_number=INT)?;
	public TransitionElements getTransitionAccess() {
		return (pTransition != null) ? pTransition : (pTransition = new TransitionElements());
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}

	//Event:
	//	"onevent" eventliteral=STRING;
	public EventElements getEventAccess() {
		return (pEvent != null) ? pEvent : (pEvent = new EventElements());
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//Function:
	//	sourcecode=STRING;
	public FunctionElements getFunctionAccess() {
		return (pFunction != null) ? pFunction : (pFunction = new FunctionElements());
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//terminal ID returns ecore::EString:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING returns ecore::EString:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT returns ecore::EString:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT returns ecore::EString:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS returns ecore::EString:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER returns ecore::EString:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
