/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RfsmUiModule extends be.kuleuven.rodinia.dsl.ui.AbstractRfsmUiModule {
	public RfsmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
