/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.ui.contentassist

import be.kuleuven.rodinia.dsl.ui.contentassist.AbstractLuaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LuaProposalProvider extends AbstractLuaProposalProvider {
}
