/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LuaStandaloneSetup extends LuaStandaloneSetupGenerated{

	public static void doSetup() {
		new LuaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

