/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.kuleuven.rodinia.dsl.services.RfsmGrammarAccess;

public class RfsmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RfsmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.kuleuven.rodinia.dsl.parser.antlr.internal.InternalRfsmParser createParser(XtextTokenStream stream) {
		return new be.kuleuven.rodinia.dsl.parser.antlr.internal.InternalRfsmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RfsmGraph";
	}
	
	public RfsmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RfsmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
