/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.validation;

import be.kuleuven.rodinia.dsl.validation.AbstractRfsmValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RfsmValidator extends AbstractRfsmValidator {
}
